version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    container_name: voicy_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voicy
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
