services:
  db:
    image: postgres:15
    container_name: voicy_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voicy
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: voicy_backend
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/voicy
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # если будет FastAPI
  bot:
    build: .
    command: /start_bot.sh
    environment:
      - PYTHONPATH=/app
      - TG_BOT_TOKEN= # токен твоего телеграм-бота
    depends_on:
      - db


volumes:
  pg_data:
